Django 4.2
torchbox/rca-wagtail-2019 pull request #978
Opened 2024-01-16 07:40 UTC by katdom13

This PR:
- Upgrades Django from ~3.2 to ~4.2
- Upgrades other packages
- Adds new migration files after Django upgrades

2024-01-17 11:51 UTC, nickmoreton requested changes
Hi @katdom13 I left a few suggestions.

2024-01-17 11:51 UTC, nickmoreton commented on .gitlab-ci.yml
> +    - postgres:12.3
**comment** Just noting that this change is OK but the file isn't used for CI

2024-01-17 11:51 UTC, nickmoreton commented on rca/settings/base.py
> +]
```suggestion
```

**suggestion** I think it's better to see the warning and at some point we should investigate a fix where this is seen.

2024-01-17 11:51 UTC, nickmoreton commented on .circleci/config.yml
> +      - image: circleci/postgres:12.3
```suggestion
      - image: circleci/postgres:12.17
```

**suggestion** The version on production is using 12.17 so maybe the docker-compose.yml file DB version could be updated too.

2024-01-18 15:53 UTC, nickmoreton commented
Hi @katdom13 This is now rebased on master.

2024-01-19 12:16 UTC, katdom13 commented
> I also saw this error when running collectstatic:
> 
> ```
> Traceback (most recent call last):
>   File "manage.py", line 10, in <module>
>     execute_from_command_line(sys.argv)
>   File "/venv/lib/python3.8/site-packages/django/core/management/__init__.py", line 442, in execute_from_command_line
>     utility.execute()
>   File "/venv/lib/python3.8/site-packages/django/core/management/__init__.py", line 436, in execute
>     self.fetch_command(subcommand).run_from_argv(self.argv)
>   File "/venv/lib/python3.8/site-packages/django/core/management/base.py", line 412, in run_from_argv
>     self.execute(*args, **cmd_options)
>   File "/venv/lib/python3.8/site-packages/django/core/management/base.py", line 458, in execute
>     output = self.handle(*args, **options)
>   File "/venv/lib/python3.8/site-packages/django/contrib/staticfiles/management/commands/collectstatic.py", line 209, in handle
>     collected = self.collect()
>   File "/venv/lib/python3.8/site-packages/django/contrib/staticfiles/management/commands/collectstatic.py", line 154, in collect
>     raise processed
> whitenoise.storage.MissingFileError: The file 'js/sockjs.js.map' could not be found with <whitenoise.storage.CompressedManifestStaticFilesStorage object at 0xffff7c71e880>.
> 
> The JS file 'js/main.js' references a file which could not be found:
>   js/sockjs.js.map
> 
> Please check the URL references in this JS file, particularly any
> relative paths which might be pointing to the wrong location.
> ```
> 
> It doesn't show when running `fab build` but could do with an investigation I think. I have a feeling it will fail when deployed.

The `main.js` that is flagged seems to be a script produced by the webpack config. It might be tricky to check this one out.

2024-01-19 12:43 UTC, nickmoreton commented
> > I also saw this error when running collectstatic:
> > ```
> > Traceback (most recent call last):
> >   File "manage.py", line 10, in <module>
> >     execute_from_command_line(sys.argv)
> >   File "/venv/lib/python3.8/site-packages/django/core/management/__init__.py", line 442, in execute_from_command_line
> >     utility.execute()
> >   File "/venv/lib/python3.8/site-packages/django/core/management/__init__.py", line 436, in execute
> >     self.fetch_command(subcommand).run_from_argv(self.argv)
> >   File "/venv/lib/python3.8/site-packages/django/core/management/base.py", line 412, in run_from_argv
> >     self.execute(*args, **cmd_options)
> >   File "/venv/lib/python3.8/site-packages/django/core/management/base.py", line 458, in execute
> >     output = self.handle(*args, **options)
> >   File "/venv/lib/python3.8/site-packages/django/contrib/staticfiles/management/commands/collectstatic.py", line 209, in handle
> >     collected = self.collect()
> >   File "/venv/lib/python3.8/site-packages/django/contrib/staticfiles/management/commands/collectstatic.py", line 154, in collect
> >     raise processed
> > whitenoise.storage.MissingFileError: The file 'js/sockjs.js.map' could not be found with <whitenoise.storage.CompressedManifestStaticFilesStorage object at 0xffff7c71e880>.
> > 
> > The JS file 'js/main.js' references a file which could not be found:
> >   js/sockjs.js.map
> > 
> > Please check the URL references in this JS file, particularly any
> > relative paths which might be pointing to the wrong location.
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > It doesn't show when running `fab build` but could do with an investigation I think. I have a feeling it will fail when deployed.
> 
> The `main.js` that is flagged seems to be a script produced by the webpack config. It might be tricky to check this one out.

Lets see if it deploys OK before we spend more time on it. Unless you think it could delay things later on?

2024-01-22 08:56 UTC, merged